name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        emacs-version:
          - 27.1
          - 27.2
          - 28.1
          - 28.2

    steps:
      - uses: actions/checkout@v2

      - uses: jcs090218/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - uses: ConorMacBride/install-package@v1
        with:
          brew: exercism
          apt: tar
          choco: exercism-io-cli

      - name: Install Exercism
        if: matrix.os == 'ubuntu-latest'
        run: |
          wget https://github.com/exercism/cli/releases/latest/download/exercism-linux-64bit.tgz
          tar -xf exercism-linux-64bit.tgz
          mv exercism /usr/local/bin

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: emacs-eask/setup-eask@master
        with:
          version: "snapshot"

      - name: Setup Exercism
        env:
          config: ${{ secrets.EXERCISM_CONFIG }}
        run: |
          mkdir -p ~/.config/exercism
          echo "$config" >> ~/.config/exercism/user.json
          exercism troubleshoot

      - name: Set workaround env var
        run: |
          echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

      - name: Run tests
        run: "make ci"
